/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class Principal extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;

    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.ponerImagen(jl_CinePolis, "src/img/cinePolis.png");
        this.rb_No.setSelected(true);

    }

    DecimalFormat df = new DecimalFormat("###.##");

    private void ponerImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();

    }

    String informacion = "";
    double totalFinal = 0;

    public void clean() {

        this.txt_nombre.setText("");
        this.cmb_CantidadDeBoletos.setSelectedIndex(0);
        //this.txt_TotalAPagar.setText("");

    }

    public void getNombre() {

        int boletos;
        double total;

        boletos = this.cmb_CantidadDeBoletos.getSelectedIndex() + 1;
        total = getPrecio();

        totalFinal = totalFinal + total;

        this.txt_TotalAPagar.setText(String.valueOf(df.format(totalFinal)));

        informacion += "- " + this.txt_nombre.getText().trim() + " \n boletos: " + String.valueOf(boletos) + " \nTotal: $" + String.valueOf(total) + "\n";

        this.txt_NombresPersonas.setText(informacion);

    }

    public double getPrecio() {

        double precio = 0, descuento = 0;
        int boletos;

        boletos = this.cmb_CantidadDeBoletos.getSelectedIndex() + 1;

        precio = boletos * 12;

        if (boletos > 5) {

            descuento = precio * 0.15;
            precio = precio - descuento;

        } else if (boletos > 2 && boletos <= 5) {

            descuento = precio * 0.10;
            precio = precio - descuento;

        }

        descuento = 0;

        if (this.rb_Si.isSelected()) {

            descuento = precio * 0.10;
            precio = precio - descuento;

        }

        return precio;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jl_CinePolis = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_TotalAPagar = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        rb_No = new javax.swing.JRadioButton();
        rb_Si = new javax.swing.JRadioButton();
        btn_IrAForm2 = new javax.swing.JButton();
        btn_Procesar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        cmb_CantidadDeBoletos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_NombresPersonas = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jl_CinePolis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 340, 90));

        jLabel2.setText("SALIDAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jLabel3.setText("CANTIDAD DE BOLETOS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel4.setText("ENTRADAS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel5.setText("NOMBRE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel6.setText("TOTAL A PAGAR:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jLabel7.setText("TARJETA CINECO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_TotalAPagar.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(txt_TotalAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 130, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 190, -1));

        grupo1.add(rb_No);
        rb_No.setText("No");
        jPanel1.add(rb_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        grupo1.add(rb_Si);
        rb_Si.setText("Sí");
        jPanel1.add(rb_Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btn_IrAForm2.setText("IR A FORM 2");
        btn_IrAForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IrAForm2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_IrAForm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        btn_Procesar.setText("PROCESAR");
        btn_Procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProcesarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        btn_Salir.setText("SALIR");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        cmb_CantidadDeBoletos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jPanel1.add(cmb_CantidadDeBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 50, -1));

        txt_NombresPersonas.setColumns(20);
        txt_NombresPersonas.setRows(5);
        jScrollPane1.setViewportView(txt_NombresPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 440, 220));

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProcesarActionPerformed

        if (this.txt_nombre.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Introduce el nombre");
            
        } else {
            this.txt_TotalAPagar.setText(String.valueOf(getPrecio()));
            getNombre();
            clean();
        }
    }//GEN-LAST:event_btn_ProcesarActionPerformed

    private void btn_IrAForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IrAForm2ActionPerformed

        Datos datos = new Datos();
        datos.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_IrAForm2ActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, "Total a pagar: " + df.format(totalFinal));
        clean();
        this.txt_TotalAPagar.setText("");
        this.txt_NombresPersonas.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_IrAForm2;
    private javax.swing.JButton btn_Procesar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JComboBox<String> cmb_CantidadDeBoletos;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_CinePolis;
    private javax.swing.JRadioButton rb_No;
    private javax.swing.JRadioButton rb_Si;
    private javax.swing.JTextArea txt_NombresPersonas;
    private javax.swing.JTextField txt_TotalAPagar;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
